# Generated by Django 6.0.2 on 2026-02-15 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('computer-science', 'Computer Science'), ('data-science', 'Data Science'), ('business', 'Business'), ('design', 'Design'), ('marketing', 'Marketing'), ('photography', 'Photography')], max_length=50)),
                ('description', models.TextField()),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to='course/')),
                ('registration_start', models.DateField()),
                ('registration_end', models.DateField()),
                ('course_start', models.DateField()),
                ('course_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
