# Generated by Django 6.0.2 on 2026-02-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingmaterial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reading_materials/'),
        ),
    ]
