# Generated by Django 6.0.2 on 2026-02-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0010_alter_readingmaterial_file"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                """
                CREATE VIRTUAL TABLE courses_fts USING fts5(
                    title,
                    description,
                    content='course_course',
                    content_rowid='id'
                );
                """,
                """
                INSERT INTO courses_fts(rowid, title, description)
                SELECT id, title, description FROM course_course WHERE status='published';
                """,
                """
                CREATE TRIGGER courses_ai AFTER INSERT ON course_course BEGIN
                    INSERT INTO courses_fts(rowid, title, description)
                    VALUES (new.id, new.title, new.description);
                END;
                """,
                """
                CREATE TRIGGER courses_ad AFTER DELETE ON course_course BEGIN
                    INSERT INTO courses_fts(courses_fts, rowid, title, description)
                    VALUES ('delete', old.id, old.title, old.description);
                END;
                """,
                """
                CREATE TRIGGER courses_au AFTER UPDATE ON course_course BEGIN
                    INSERT INTO courses_fts(courses_fts, rowid, title, description)
                    VALUES ('delete', old.id, old.title, old.description);
                    INSERT INTO courses_fts(rowid, title, description)
                    VALUES (new.id, new.title, new.description);
                END;
                """,
            ],
            reverse_sql=[
                "DROP TRIGGER IF EXISTS courses_au;",
                "DROP TRIGGER IF EXISTS courses_ad;",
                "DROP TRIGGER IF EXISTS courses_ai;",
                "DROP TABLE IF EXISTS courses_fts;",
            ],
        )
    ]
