# Generated by Django 6.0.2 on 2026-02-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_fts_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomaterial',
            name='transcript',
            field=models.TextField(blank=True),
        ),
    ]
