# Generated by Django 6.0.2 on 2026-02-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('material', 'Material'), ('enrollment', 'Enrollment'), ('status', 'Status')], max_length=20),
        ),
    ]
